### ISSUE TITLE
Include Read the Docs

### ISSUE THREAD

**Issue by OddBloke** [chrisparnin/docsight#1]
An awful lot of Python documentation is held at https://readthedocs.org/ (and its sub-domains); it'd be good to include these visits.

**Comment by chrisparnin** [comment]
Yes.  I've gotten several requests for python related development.  Will be in next update.

**Comment by lwburk** [comment]
Have you gotten very far on a general solution to this problem? I'd suggest using something like this:

https://code.google.com/p/greasemonkey/source/browse/trunk/chrome/chromeFiles/content/convert2RegExp.js?r=2

It was originally developed for AdBlock and is now used (in modified form) in Greasemonkey (and other, projects, I'm sure). It's a simple, general solution that uses a format many developers will have already seen. I'm happy to help out, as well, if you've got other features on your plate.

**Comment by chrisparnin** [comment]
@lwburk This could be a nice approach for custom urls, using the @include/@exclude patterns.  

One problem with including a new url is the favicon.  Chrome stores the fav_icon in the history database.  But the extensions cannot directly access that.  There is a `chrome://favicon/example.com/`, which can be used to fetch the stored favicon of example.com.  This doesn't work from a sandboxed part of extension (which you need if using templates). It is also flaky and doesn't work unless the page has been just visited.  Fetching the favicon from the web would not work due to permissions.

Until there is a more streamlined way to get favicons, i'll still be adding included sites for now.

**Comment by chrisparnin** [comment]
Thanks to this issue and comments there has been an overhaul on how filtering works.  Version 1.0.4 now has much more developer sites supported and a streamlined way to represent the site matching patterns.

I still want to allow custom inclusions, which is outside of the scope of this issue, so I've opened up the following issue:

```
  https://github.com/chrisparnin/docsight/issues/4
```
